### ISSUE TITLE
Support forwarding of IEvent<T> from Marten in addition to the T

### ISSUE THREAD

**Issue by koenmetsu** [JasperFx/wolverine#132]
Would be great to add support for handling via the interface of a type, instead of just the concrete type.
```
public class MartenEventsConsumer : IMartenEventsConsumer
{
    private readonly IServiceProvider _serviceProvider;

    public MartenEventsConsumer(IMessageBus bus)
      => _bus = bus;

    public async Task ConsumeAsync(IReadOnlyList<StreamAction> streamActions)
      => foreach (var @event in streamActions.SelectMany(streamAction => streamAction.Events))
              _bus.Send(@event) ==> // this doesn't work
             _bus.Send(@event.Data) ==> // this does
}

public class ElasticEventHandler
{
    public async Task Handle(IEvent<MyEvent> message)
        => // doesn't get here;

    public async Task Handle(MyEvent message)
        => // this works;
}
```

**Comment by jeremydmiller** [comment]
I think this is turning into a bigger post-1.0 story about optimizing the event publishing and this is going to go into 1.1. Also probably gets done at the same time as the daemon subscription integration

Ideas:

Optimized strategy per event type like:

```csharp

internal interface IMartenEventPublisher
{
    ValueTask PublishAsync(IEnumerable<IEvent> events, IMessageBus bus);
}
```

* That would already pre-routed, so that the real thing is either a nullo, do nothing, or publishes immediately through MessageRoute and bypasses a lot of the existing MessageBus.PublishAsync() method. 

* Also, introduce the idea of event filtering. 
* Transformers to other message shapes, including using IEvent<T> as either the destination or the transformation source
* Type filtering off of the `EventForwardingToWolverine` syntax

**Comment by jeremydmiller** [comment]
## Test Cases

- [ ] Can still automatically forward messages from IEvent<T> to T
- [ ] Directly handle `IEvent<T>`
- [ ] Custom transformation of `IEvent<T>` to a different type
