### ISSUE TITLE
Support Host.CreateApplicationBuilder

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#171]
Every new version of .NET gives us a new bootstrapping mechanism. `UseWolverine()` today depends on `IHostBuilder` and won't help w/ `Host.CreateApplicationBuilder()`

**Comment by jeremydmiller** [comment]
Putting this off for a bit. Going to be way annoying for very little value.

**Comment by mark-branchboston** [comment]
> Going to be way annoying for very little value.

I _might_ have a value proposition for you assuming I understand the issue properly.

I am trying to integrate Wolverine with OrchardCore. Since Wolverine does all of its service orchestration in the same extension that requires the host builder reference, it isn't possible (AFAICT) to register the services in a way that is visible to an OrchardCore tenant which would allow my Wolverine endpoints to see and use services registered by OrchardCore.

I think if `AddLamar()` (the primary dependency that needs the host builder for swapping out the service provider) was separate, it would then be possible to call `UseWolverine()` as an IServiceCollection extension instead. Of course there is still the issue of the customization action that runs _after_ service orchestration that still depends on the host builder. Not sure what to suggest there.

I have an [SO article around this very issue](https://stackoverflow.com/questions/77136382/how-can-i-configure-wolverine-for-use-with-orchardcore) with an MRE repo linked at the bottom.

**Comment by daerogami** [comment]
> Going to be way annoying for very little value.

I _might_ have a value proposition for you assuming I understand the issue properly.

I am trying to integrate Wolverine with OrchardCore. Since Wolverine does all of its service orchestration in the same extension that requires the host builder reference, it isn't possible (AFAICT) to register the services in a way that is visible to an OrchardCore tenant which would allow my Wolverine endpoints to see and use services registered by OrchardCore.

I think if `AddLamar()` (the primary dependency that needs the host builder for swapping out the service provider) was separate, it would then be possible to call `UseWolverine()` as an IServiceCollection extension instead. Of course there is still the issue of the customization action that runs _after_ service orchestration that still depends on the host builder. Not sure what to suggest there.

I have an [SO article around this very issue](https://stackoverflow.com/questions/77136382/how-can-i-configure-wolverine-for-use-with-orchardcore) with an MRE repo linked at the bottom.

**Comment by Hookyns** [comment]
Hello,

.NET MAUI has custom [MauiAppBuilder](https://github.com/dotnet/maui/blob/c4479e66d0f948c380cee30a4f7e58694afc0453/src/Core/src/Hosting/MauiAppBuilder.cs) and there is no HostBuilder at all so it's not possible to use Wolverine with MAUI. 

Looking at the `UseWolverine()` implementation, there should be no problem to create second extension method for `IServiceCollection` or `MauiAppBuilder` but `UseLamar()` requires HostBuilder too. There is method `ConfigureContainer` on the MAUI's builder, it allows to set custom `IServiceProviderFactory`, idk if it's the only problem.

**Comment by mgamache** [comment]
CreateApplicationBuilder is the default for background workers so it would be nice to add UseWolverine(). I will be looking for an alternative unfortunately.

**Comment by jeremydmiller** [comment]
I think this is going to be ultimately linked to the removal of Lamar as a hard dependency
