### ISSUE TITLE
AssertConfigurationIsValid() not validating Lamar container effectively in Wolverine

### ISSUE THREAD

**Issue by mfuqua3** [JasperFx/wolverine#270]
The AssertConfigurationIsValid() helper method is not effectively validating Wolverine's backing Lamar container because it doesn't attempt to resolve the Wolverine handlers. This can lead to potential runtime errors that could have been caught during the configuration validation phase.

Steps to reproduce:

1. Create a new Wolverine project.
2. Add a WolverineHandler to the project
3. Add a dependency to the handler that is not registered with container
4. Call AssertConfigurationIsValid() to validate the container's configuration.
5. Run the application and attempt to resolve the handler.
6. Observe that the handler cannot be resolved, even though AssertConfigurationIsValid() reported no errors.

Expected behavior:

AssertConfigurationIsValid() should effectively validate the Lamar DI container by attempting to resolve all registered dependencies, including Wolverine handlers.

Proposed solution:

Add an option to Wolverine handler discovery to register all handlers as instances within the DI container, that can enabled by integration tests to validate the container.

**Comment by jeremydmiller** [comment]
@mfuqua3,

Finally thinking more about this. It doesn't actually help much in a way, because the Wolverine handler discovery actually happens in an `IHostedService.StartAsync()` method and can't really be calculated until then. You *could* however, use your own custom `IRegistrationConvention` to do this *now*, but make sure the handlers are added with `Scoped` as the lifetime.

This also doesn't help if you're using Wolverine idiomatically where Wolverine wants you to eschew DI and use pure functions and/or use method injection. I'm going to add a Wolverine equivalent to Lamar's AssertConfigurationIsValid() for `IHost` that would do something similar for Wolverine that would also address the issues you mentioned.
