### ISSUE TITLE
Make a note in Saga documentation to not use InvokeAsync() within a saga handler against the current saga

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#277]
Won't work, have folks use cascading messages instead.

**Comment by agross** [comment]
It would be great if you could provide an example of what won't work. I get "saga not found" errors when I `InvokeAsync<Cascaded>(MessageIdentifyingAsSaga)`, but it works with `InvokeAsync(MessageIdentifyingAsSaga)`.

**Comment by jeremydmiller** [comment]
Think about it. The InvokeAsync() runs inline, so it executes in a completely different context *right at that moment* independently of whatever is going on in the first handler. So you either haven't saved a new saga, or you're working against an old copy of the existing saga in the case where it "worked". 

Now you've got me thinking that the message context needs to throw an invalid exception on this to stop this usage.

**Comment by agross** [comment]
How would you move a saga forward if e.g. a command was received via an API? This is my use case. The saga exists and is not completed yet. Now, something interesting happens in the frontend, the backend receives an HTTP request (a command), and that command should cause a saga handler to run.

I can't work directly with an aggregate (`FetchForWriting`) since the domain object that the saga represents an entity. The saga stores the aggregate ID the entity belongs to, loads the aggregate (`FetchForWriting`), and issues a call against it, eventually invoking a method on the entity.

I want the saga handler to return the event that has been returned by that aggregate method call.

> whatever is going on in the first handler

There is no temporal ordering in my example above. Just 2 variants of the same invocation.

**Comment by jeremydmiller** [comment]
Why would your new command not be applicable to an existing saga? The problem I'm stating above is trying to invoke a command **inline** within another saga message handler that is in the middle of an operation. You just need to publish a new message -- which is what a cascading message does -- to act further on the saga. You *can* invoke an unrelated command I guess, but that's pretty slow and you lose all transactional integrity. 

So the initial command creates the saga, completes, then publishes the additional steps.

**Comment by jeremydmiller** [comment]
And I don't think I'd recommend mixing an aggregate and a saga. I think you're best off treating the write model of the event stream as a de facto stateful saga. Even gives you better concurrency protection w/ the Marten mechanisms than Wolverine has today w/ sagas.

**Comment by agross** [comment]
OK, perhaps we're talking about different topics. I think I was misled by the issue title.

* I don't `InvokeAsync` "inside" the saga handler and I don't plan to.
* In my [second comment](https://github.com/JasperFx/wolverine/issues/277#issuecomment-1492083215) I said that when, from outside of the saga, I `InvokeAsync` that invocation succeeds against an existing saga, but `InvokeAsync<T>` does not (Saga not found _after_ running the saga handler).
* > And I don't think I'd recommend mixing an aggregate and a saga.
   
  I don't know how I could load the aggregate from the entity's ID since it's "buried" inside the aggregate's events. But since the saga executes against the aggregate anyway the same concurrent protection is applied, as least as far as I understand. Perhaps it's a special case, but the solution seems to work OK.

**Comment by jeremydmiller** [comment]
"I don't InvokeAsync "inside" the saga handler and I don't plan to." -- cool, I think we're on the same page.

"In my https://github.com/JasperFx/wolverine/issues/277#issuecomment-1492083215 I said that when, from outside of the saga, I InvokeAsync that invocation succeeds against an existing saga, but InvokeAsync<T> does not (Saga not found after running the saga handler)." -- I'm going to have to see more context. That's the exact same issue though if you're invoking something else on the saga, no state has yet been persisted. Or what am I missing that you're trying to tell me here?

"I don't know how I could load the aggregate from the entity's ID since it's "buried" inside the aggregate's events. But since the saga executes against the aggregate anyway the same concurrent protection is applied, as least as far as I understand. Perhaps it's a special case, but the solution seems to work OK." -- my recommendation would be to try to use the event stream as your de facto saga, so the "aggregate" in this case is always the stream id. Or are we using the word "aggregate" the same way? I'm only visualizing that as the projected state of an event stream.

**Comment by jeremydmiller** [comment]
@agross ^^^ didn't tag you before, sorry

**Comment by agross** [comment]
> I'm going to have to see more context. That's the exact same issue though if you're invoking something else on the saga, no state has yet been persisted.

The saga handler roughly looks like this (didn't try to see if it compiles):

```csharp
public record SomeCommand([property: SagaIdentity]
                             string TheSagaId)

 public async Task<SomeEvent> Handle(SomeCommand command, IDocumentSession session, CancellationToken ct)
 {
  return session.FetchForWriting<SomeAggregate>(this.SomeAggregateId).Aggregate.CallMethodOnEntity(command.TheSagaId);
  // TheSagaId identifies one of SomeAggregate's entities.
 }
```

From the HTTP layer I can either:

```csharp
IMessageBus.InvokeAsync(new SomeCommand(sagaId));
```

which works.

Or:

```csharp
IMessageBus.InvokeAsync<SomeEvent>(new SomeCommand(sagaId));
```

which first runs the handler to completion (I set a breakpoint) and then tells me the saga was not found.

> Or are we using the word "aggregate" the same way? I'm only visualizing that as the projected state of an event stream.

IMHO the aggregate is the consistency boundary. That boundary in my case contains one or more entities that users can act upon - but always passing the user's request through the aggregate.

The user won't know the aggregate's ID, but the ID of "their" entity. I use the saga to store the aggregate's ID to be able to load it.

Those entities should also be acted upon based on timeouts.

In my case, aggregate and entity state is represented by an event stream - which should be the same as your statement above: "as the projected state of an event stream".

If you still like more context I can try to explain the concrete solution and why I think the entities can't be aggregate streams.

**Comment by agross** [comment]
> didn't tag you before, sorry

Thank you, but that is not needed! I'm subscribed to stuff I comment on and the other stuff that I just watch ;-)
