### ISSUE TITLE
Runtime Rabbit MQ configuration options

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#328]
Ability to dynamically connect a new device at runtime that will require a new exchange/binding/queue. Programmatically add new objects & listener. Also an ability to retire the subscription and remove listeners and maybe even routing table from Wolverine to reclaim memory

**Comment by jessestr** [comment]
Any update on this?

**Comment by jessestr** [comment]
As asked by Jeremy to put the request into detail:

- Everything should be doable outside the initial Wolverine config
- Allow for creating bindings from an exchange to a queue at runtime 
- Allow for removing bindings from an exchange to a queue at runtime

In my use case (IoT platform) this would allow me to adopt (bind) to different devices (exchanges) where I am interested in in my consumer (queue). 

My consumer has a queue where it listens to, and every exchange it's interested in it should get a binding from that exchange to that specific queue. However this should be done at runtime. Since "adopting a device" is a business case and upon adopting this device I need to be able to create bindings. 

If you adopt the device it should be possible to call for a remove binding.

**Comment by jeremydmiller** [comment]
@jessestr If you're interested, there's a remote branch now named `dynamic-rabbit-objects` that has the conceptual code for creating objects on the fly. There's nothing for "un-binding", but that's not a lot of code. At this point, I still want to ask if you'll push this through as this is pretty well for your specific system

**Comment by jessestr** [comment]
@jeremydmiller I will check out the code later today, thanks for adding this! 
About pushing this through... well it's not like specifically for my system. In other libraries or message brokers like ASB, you can easily create subscriptions on the fly and remove them. I think it might be valuable to add this to Wolverine since in IoT projects you might need this.

I'll report back when done testing.

**Comment by jessestr** [comment]
@jeremydmiller Is it me or is the code just for creating exchanges/queues on the fly? Since I was more looking on creation the actual binding between the exchange / queue on the fly.

**Comment by jeremydmiller** [comment]
Really just needing to bind an exchange, queue, binding triplet combo on the fly, and also tear it down.
