### ISSUE TITLE
Kafka Transport?

### ISSUE THREAD

**Issue by tkolo** [JasperFx/wolverine#390]
I've noticed the absence of kafka as transport method. While this issue is also a request to perhaps support it, first I wanted to ask: Is kafka technically a viable transport for wolverine? My understanding is that I'd be ideal as not only it can forward messages to appropriate recipients, but also serve as database given how it's client's choice at which offset to start fetching messages from topic. But perhaps I'm missing a point on how a transport is supposed to work?

**Comment by jeremydmiller** [comment]
A Kafka transport is definitely planned, occasionally asked for, probably immediately valuable for Marten subscription support right after Wolverine 1.0, but mostly this:

![image](https://github.com/JasperFx/wolverine/assets/179211/636a68d2-1116-4b38-b1f2-e09d081bb7f3)

Wanna volunteer? There actually was a Jasper (Wolverine's ancestor) transport for Kafka, and I think it would closely resemble the Pulsar transport in Wolverine today.

**Comment by JeffryGonzalez** [comment]
Kafka is definitely the missing piece for a lot of my work. A basic implementation based on the Pulsar stuff, like you suggested, would be a good start, and I even got a version of it somewhat working once, but the big requirement for me would be support for SchemaRegistry. The Confluent packages are ok for this, and I even wrote a quick abstraction around it a couple of years ago (it's in a private repo, but if it would be helpful, I could open it up, and even update it.). It supports Avro and Protobuf, because that's what we use, but would probably need to add the serdes for JsonSchema as well.  As I recall, the Avro/Protobuf is super straight forward, but the JsonSchema stuff was a whole other world. Happy to share some code/what I've learned if the project gets this deep into it.

**Comment by murbanowicz** [comment]
@jeremydmiller adding it here as I didn't manage to get here after you've asked for input, but before you merged initial support (your work is just amazing).

**Schema support** - one of great benefits of Kafka is schema support - either JSON Schema or Avro (more standard). It would be really nice if Wolverine would support it.
