### ISSUE TITLE
Is it possible return tuple from handler?

### ISSUE THREAD

**Issue by sharpzilla** [JasperFx/wolverine#454]
Hello, I want to return tuuple (boll, MyClass) but there is default return instead;

Here is handler code:
```
public class GetRegularTaskHandler
{
	public async Task<(bool, MyClass?)> HandleAsync(GetRegularTaskCommand command,
									 ILogger logger,
									 Client client,
									 CancellationToken cancellationToken)
	{
		MyClass? response = await client.GetTask(command.TaskName, cancellationToken);
//code is simplified
		return (true, task);
	}
}
```

From client I'm receiving some task in response. But in my code where I need result of processed command, there is **false** and **null**:
`var result = await _bus.InvokeAsync<(bool, MyClass?)>(new GetRegularTaskCommand(_jobSettings.TaskName), cancellationToken);`

**Comment by jeremydmiller** [comment]
That's not exactly a usage that's supported. There's quite a bit of documentation and samples on handler signatures that show Tuple usage. Wolverine treats every single value of the tuple as a completely separate "return value", but does not recognize the actual Tuple type as a return value. So in the code above, you could have used InvokeAsync<bool>() (not sure that would work since bool is a struct though) or InvokeAsync<MyClass>().

**Comment by jeremydmiller** [comment]
Feel like this one's answered, so closing
