### ISSUE TITLE
UseNewtonsoftForSerialization does not have any effect

### ISSUE THREAD

**Issue by nkosi23** [JasperFx/wolverine#508]
I use Wolverine from F# and need to use Newtonsoft for serialization since System.Text.Json does not support the serialization of discriminated union types (the exception: "NotSupportedException:  F# discriminated union serialization is not supported" is thrown)

However, calling UseNewtonsoftForSerialization() does not seem to have any effect since the exception is still being thrown and apparently Wolverine still uses System.Text.Json considering the debug log.

```csharp
// Wolverine usage is required for WolverineFx.Http
builder.Host.UseWolverine(opts =>
{
    // This middleware will apply to the HTTP
    // endpoints as well
    opts.Policies.AutoApplyTransactions();

    // Setting up the outbox on all locally handled
    // background tasks
    opts.Policies.UseDurableLocalQueues();

    opts.UseNewtonsoftForSerialization();

});
```

> NotSupportedException: F# discriminated union serialization is not supported. Consider authoring a custom converter for the type.
>System.Text.Json.Serialization.Converters.FSharpTypeConverterFactory.CreateConverter(Type typeToConvert, JsonSerializerOptions option

**Comment by jeremydmiller** [comment]
Can you put the full stack trace in there so I can see where exactly it didn't replace STJ?

**Comment by jeremydmiller** [comment]
Oh, okay, this makes sense to me now. The **Wolverine.HTTP** serialization just uses whatever Minimal API has configured for serialization. Let's keep this open as an enhancement request. It's not exactly trivial, but we'll have to do something for Wolverine itself. Newtonsoft is a touch more complicated to use because you have to deal with this or that pool yourself.

I'm a little shocked to learn that Minimal API doesn't support Newtonsoft? That surprised me.
