### ISSUE TITLE
Postgres Transport?

### ISSUE THREAD

**Issue by AndyPook** [JasperFx/wolverine#518]
Given Marten is dependent on postgres, it is a surprise (to me) that there is not an out-of-box transport for pg, but there is one for mssql 🤔

**Comment by jeremydmiller** [comment]
See https://github.com/JasperFx/wolverine/issues/224, it's in the backlog

Because a client paid for my time to build the Sql Server option:-) The PostgreSQL version will happen at some point. Somebody took a shot at it, but it didn't get all the way in. The postgres flavor might end up being a little more robust with the theory that you can use PG_NOTIFY to "push" a little bit.

**Comment by cjabbour** [comment]
A PG version would be awesome! Exactly what my team is looking for. Preferably an option that doesn't "need to" build out any new tables/objects at runtime. Thanks for all the hard work!
