### ISSUE TITLE
AddDbContextWithWolverineIntegration and interceptors

### ISSUE THREAD

**Issue by GhislainL** [JasperFx/wolverine#547]
Hi,

thanks for your work. 
I'm trying to use Wolverine with EF Core in order to implement mediator and outbox pattern in an web application.

I have the following code : 
`builder.Services.AddDbContext<ApplicationDbContext>((sp, options) =>
{
    options.AddInterceptors(sp.GetServices<ISaveChangesInterceptor>());
    options.UseSqlServer(connectionString);
});
`

one of the interceptor's constructor needs parameters so i can't pass a new instance, like options.AddInterceptors(new MyInterceptor()) 

I can't transpose this with Wolverine because there is no parameter of type Action<IServiceProvider, DbContextOptionsBuilder> for AddDbContextWithWolverineIntegration().

It might be the following lines if it has the same effects : 
`builder.Services.AddDbContext<ApplicationDbContext>((sp, options) =>
{
    options.AddInterceptors(sp.GetServices<ISaveChangesInterceptor>());
    options.UseSqlServer(connectionString);
}, ServiceLifetime.Scoped, ServiceLifetime.Singleton);
`
Could you please give me an hint please ?

Regards,

Ghislain

**Comment by jeremydmiller** [comment]
You're going to have to bypass the Wolverine specific registration for now and integrate the outbox yourself. Sorry.

I don't think this is likely anything that we'd support directly in the future because any kind of runtime resolution via `IServiceProvider` pretty well wipes out the Wolverine IoC optimizations.

What are you doing in your DbContext interceptors? Something that could be Wolverine middleware instead?
