### ISSUE TITLE
How-to publish multiple events looping over a list

### ISSUE THREAD

**Issue by Martin-Andersen** [JasperFx/wolverine#774]
First, I would like to say that I love 😍 the syntax.

At my company we are using NSB, but after looking at Wolverine I think it's time to try something new.

We have many handlers that receive a list of items, and for each item we publish an internal message using _messageSession.SendLocal().

I have looked at this example [Only Publish Messages from the Root Handler Method](https://wolverine.netlify.app/tutorials/best-practices.html#only-publish-messages-from-the-root-handler-method). Is this the best way?

Have tried to join the discord channel. But could not get it to work. Error msg. Invite link is to old

**Comment by jeremydmiller** [comment]
Try this: https://discord.gg/critter-stack-net-1074998995086225460

You *can* just make your method signature return `IEnumerable<object>` and let Wolverine send each as an outgoing message. I like that because it turns into a `foreach / yield return` kinda thing. Can also use `OutgoingMessages`, that's pretty slick now with the collection initializer stuff in recent C# versions.

Biggest thing -- and this came out of my experience with a system using NServiceBus -- is to make it as obvious as possible from a quick look at your handler code what messages might be spawned from your original message. I like the cascading message approach myself: https://wolverine.netlify.app/guide/handlers/cascading.html
