### ISSUE TITLE
Can't configure existing ASB topic/subs without provisioning anything by wolverine

### ISSUE THREAD

**Issue by dzejsien** [JasperFx/wolverine#789]
I have IaC's topics and subs. **I don't want to create anything in Azure by runtime code** (who generally does that?).

I'm using the code

using var host = Host.CreateDefaultBuilder()
    .UseWolverine(opts =>
    {
        opts.UseAzureServiceBus(ConnString);
        //opts.OnAnyException().MoveToErrorQueue(); -- ?? is it needed?
       
        //.AutoProvision(); - on purpose!

        opts.PublishMessage<DeviceLifecycleEvent>().ToAzureServiceBusTopic("device-lifecycle-events");

        opts.ListenToAzureServiceBusSubscription("device-management")
            .FromTopic("device-lifecycle-events");
    })

I want to configure consumers of subscriptions. Moreover, I don't publish messages too - those can be subscriptions for internal Azure events. 

I'm receiving errors:

"Error while trying to retrieve messages from Azure Service Bus asb://queue/wolverine.retries.hostnet8. Check if system queues should be enabled for this application because this could be from the application being unable to create the system queues for Azure Service Bus"

and

"Azure.Messaging.ServiceBus.ServiceBusException: Put token failed. status-code: 404, status-description: The messaging entity 'sb://***.servicebus.windows.net/wolverine.response.-1203233731' could not be found."

Please let me know if this is possible at all. Thanks!

**Comment by dzejsien** [comment]
Looks like I found the needed option:

opts.UseAzureServiceBus(ConnString).SystemQueuesAreEnabled(false);

I'm receiving an event, but a new ex appears: "The envelope has no Message or MessageType name".

I understood, that I should indicate EventType - I assumed that I should do this by line:

opts.PublishMessage<DeviceLifecycleEvent>().ToAzureServiceBusTopic("device-lifecycle-events");

Pls support.

**Comment by dzejsien** [comment]
There is probably some convention behind that, but not sure what is it.

https://github.com/JasperFx/wolverine/blob/main/src/Wolverine/Transports/EnvelopeMapper.cs#L81

public void MapIncomingToEnvelope(Envelope envelope, TIncoming incoming)
    {
        _mapIncoming.Value(envelope, incoming);
// <---- envelope doesn't have MessageType and Message
        var contentType = envelope.ContentType; 
        var serializer = _endpoint.TryFindSerializer(contentType) ?? _endpoint.DefaultSerializer;
        envelope.Serializer = serializer;
    }

**Comment by jeremydmiller** [comment]
@dzejsien Okay, there's a lot to unpack here. First off, the `AutoProvision()` is very commonly used, and that's a way to go faster. If AutoProvision is off, it's not doing anything to create queues or topics. I don't believe the system queues are enabled by default, but I can double check that. 

I assume somewhere, some how you're trying to use request/reply with Wolverine over ASB? In that case, you would absolutely need to allow Wolverine to create those temporary reply queues. Which again, is a very, very common usage.

Is something on the other side trying to send to Wolverine that isn't Wolverine? That could explain the "The envelope has no Message or MessageType name" issue. Ways around that if necessary of course if it's an interop situation.

Hey, since this is mostly questions, could you please use Discord instead? I'm asking folks to not use GitHub issues strictly for questions. Try: https://discord.com/channels/1074998995086225460/1074999099855753317
